api_platform:
    title: MTG Store API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    patch_formats:
        json: ['application/merge-patch+json', 'application/json']
