framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            App\Message\ProcessCsvImportMessage: async
            App\Message\SyncScryfallCatalogMessage: async
