<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260629043851 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE order_lines (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, card_name VARCHAR(255) NOT NULL, quantity INT NOT NULL, price_cents INT NOT NULL, order_id INT NOT NULL, card_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CC9FF86B8D9F6D38 ON order_lines (order_id)');
        $this->addSql('CREATE INDEX IDX_CC9FF86B4ACC9A20 ON order_lines (card_id)');
        $this->addSql('CREATE TABLE orders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(32) NOT NULL, status VARCHAR(255) NOT NULL, customer_name VARCHAR(255) DEFAULT NULL, customer_email VARCHAR(255) DEFAULT NULL, total_cents INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, store_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E52FFDEEAEA34913 ON orders (reference)');
        $this->addSql('CREATE INDEX IDX_ORDER_STORE ON orders (store_id)');
        $this->addSql('ALTER TABLE order_lines ADD CONSTRAINT FK_CC9FF86B8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_lines ADD CONSTRAINT FK_CC9FF86B4ACC9A20 FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEEB092A811 FOREIGN KEY (store_id) REFERENCES stores (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cards ADD set_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ADD colors JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ADD color_identity JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ADD keywords JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ADD power VARCHAR(16) DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ADD toughness VARCHAR(16) DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ADD loyalty VARCHAR(16) DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ADD artist VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ADD flavor_text TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ADD legalities JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ADD finishes JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ADD games JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ADD released_at DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ADD lang VARCHAR(16) DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ADD layout VARCHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ADD scryfall_uri VARCHAR(512) DEFAULT NULL');
        $this->addSql('ALTER TABLE cards ADD scryfall_data JSON DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE order_lines DROP CONSTRAINT FK_CC9FF86B8D9F6D38');
        $this->addSql('ALTER TABLE order_lines DROP CONSTRAINT FK_CC9FF86B4ACC9A20');
        $this->addSql('ALTER TABLE orders DROP CONSTRAINT FK_E52FFDEEB092A811');
        $this->addSql('DROP TABLE order_lines');
        $this->addSql('DROP TABLE orders');
        $this->addSql('ALTER TABLE cards DROP set_name');
        $this->addSql('ALTER TABLE cards DROP colors');
        $this->addSql('ALTER TABLE cards DROP color_identity');
        $this->addSql('ALTER TABLE cards DROP keywords');
        $this->addSql('ALTER TABLE cards DROP power');
        $this->addSql('ALTER TABLE cards DROP toughness');
        $this->addSql('ALTER TABLE cards DROP loyalty');
        $this->addSql('ALTER TABLE cards DROP artist');
        $this->addSql('ALTER TABLE cards DROP flavor_text');
        $this->addSql('ALTER TABLE cards DROP legalities');
        $this->addSql('ALTER TABLE cards DROP finishes');
        $this->addSql('ALTER TABLE cards DROP games');
        $this->addSql('ALTER TABLE cards DROP released_at');
        $this->addSql('ALTER TABLE cards DROP lang');
        $this->addSql('ALTER TABLE cards DROP layout');
        $this->addSql('ALTER TABLE cards DROP scryfall_uri');
        $this->addSql('ALTER TABLE cards DROP scryfall_data');
    }
}
