<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Case Cards v2: named display cases (store_cases) containing sections,
 * per-section inventory pools (quantity/sold_quantity on section cards),
 * richer auto-fill filters (color identity, set, card type), and case
 * provenance on order lines for pull sheets / print sheets.
 *
 * Existing sections are migrated into a default "Display Case" per store.
 */
final class Version20260720032341 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Case Cards v2: display cases, section pools, filter columns, order-line case provenance';
    }

    public function up(Schema $schema): void
    {
        // New case level: store → cases → sections.
        $this->addSql('CREATE TABLE store_cases (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, store_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_60255592B092A811 ON store_cases (store_id)');
        $this->addSql('CREATE INDEX idx_store_cases_store_position ON store_cases (store_id, position)');
        $this->addSql('ALTER TABLE store_cases ADD CONSTRAINT FK_60255592B092A811 FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE NOT DEFERRABLE');

        // Section auto-fill filters + case membership. case_id is added
        // nullable, backfilled via a default case per store, then locked down.
        $this->addSql('ALTER TABLE store_sections ADD auto_color_identity VARCHAR(8) DEFAULT NULL');
        $this->addSql('ALTER TABLE store_sections ADD auto_set_code VARCHAR(16) DEFAULT NULL');
        $this->addSql('ALTER TABLE store_sections ADD auto_card_type VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE store_sections ADD case_id INT DEFAULT NULL');
        $this->addSql("INSERT INTO store_cases (name, position, created_at, store_id) SELECT DISTINCT 'Display Case', 0, NOW(), store_id FROM store_sections");
        $this->addSql('UPDATE store_sections s SET case_id = k.id FROM store_cases k WHERE k.store_id = s.store_id');
        $this->addSql('ALTER TABLE store_sections ALTER case_id SET NOT NULL');
        $this->addSql('ALTER TABLE store_sections ADD CONSTRAINT FK_15E13C62CF10D4F5 FOREIGN KEY (case_id) REFERENCES store_cases (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_15E13C62CF10D4F5 ON store_sections (case_id)');

        // Per-section inventory pool: allocated copies + copies sold from the pool.
        $this->addSql('ALTER TABLE store_section_cards ADD quantity INT DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE store_section_cards ADD sold_quantity INT DEFAULT 0 NOT NULL');

        // Order-line case provenance: live FK for pool restore on cancel/refund,
        // plus name snapshots that survive a section/case being dismantled.
        $this->addSql('ALTER TABLE order_lines ADD case_name VARCHAR(120) DEFAULT NULL');
        $this->addSql('ALTER TABLE order_lines ADD section_title VARCHAR(120) DEFAULT NULL');
        $this->addSql('ALTER TABLE order_lines ADD case_quantity INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE order_lines ADD section_card_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE order_lines ADD CONSTRAINT FK_CC9FF86B988B572F FOREIGN KEY (section_card_id) REFERENCES store_section_cards (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_CC9FF86B988B572F ON order_lines (section_card_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE order_lines DROP CONSTRAINT FK_CC9FF86B988B572F');
        $this->addSql('DROP INDEX IDX_CC9FF86B988B572F');
        $this->addSql('ALTER TABLE order_lines DROP case_name');
        $this->addSql('ALTER TABLE order_lines DROP section_title');
        $this->addSql('ALTER TABLE order_lines DROP case_quantity');
        $this->addSql('ALTER TABLE order_lines DROP section_card_id');
        $this->addSql('ALTER TABLE store_section_cards DROP quantity');
        $this->addSql('ALTER TABLE store_section_cards DROP sold_quantity');
        $this->addSql('ALTER TABLE store_sections DROP CONSTRAINT FK_15E13C62CF10D4F5');
        $this->addSql('DROP INDEX IDX_15E13C62CF10D4F5');
        $this->addSql('ALTER TABLE store_sections DROP auto_color_identity');
        $this->addSql('ALTER TABLE store_sections DROP auto_set_code');
        $this->addSql('ALTER TABLE store_sections DROP auto_card_type');
        $this->addSql('ALTER TABLE store_sections DROP case_id');
        $this->addSql('ALTER TABLE store_cases DROP CONSTRAINT FK_60255592B092A811');
        $this->addSql('DROP TABLE store_cases');
    }
}
