<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260719025936 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add store_sections and store_section_cards for the Case Cards feature';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE store_section_cards (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, section_id INT NOT NULL, inventory_item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B236A207D823E37A ON store_section_cards (section_id)');
        $this->addSql('CREATE INDEX IDX_B236A207536BF4A2 ON store_section_cards (inventory_item_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_section_inventory_item ON store_section_cards (section_id, inventory_item_id)');
        $this->addSql('CREATE TABLE store_sections (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(120) NOT NULL, position INT NOT NULL, mode VARCHAR(16) NOT NULL, auto_min_price_cents INT DEFAULT NULL, auto_max_price_cents INT DEFAULT NULL, auto_rarity VARCHAR(20) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, store_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_15E13C62B092A811 ON store_sections (store_id)');
        $this->addSql('CREATE INDEX idx_store_sections_store_position ON store_sections (store_id, position)');
        $this->addSql('ALTER TABLE store_section_cards ADD CONSTRAINT FK_B236A207D823E37A FOREIGN KEY (section_id) REFERENCES store_sections (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE store_section_cards ADD CONSTRAINT FK_B236A207536BF4A2 FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE store_sections ADD CONSTRAINT FK_15E13C62B092A811 FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE store_section_cards DROP CONSTRAINT FK_B236A207D823E37A');
        $this->addSql('ALTER TABLE store_section_cards DROP CONSTRAINT FK_B236A207536BF4A2');
        $this->addSql('ALTER TABLE store_sections DROP CONSTRAINT FK_15E13C62B092A811');
        $this->addSql('DROP TABLE store_section_cards');
        $this->addSql('DROP TABLE store_sections');
    }
}
