<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260703090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Customer in-app notifications for fulfilled orders';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE customer_notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, store_id INT NOT NULL, related_order_id INT DEFAULT NULL, type VARCHAR(64) NOT NULL, title VARCHAR(255) NOT NULL, body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CUSTOMER_NOTIFICATION_USER_STORE ON customer_notifications (user_id, store_id)');
        $this->addSql('CREATE INDEX IDX_CUSTOMER_NOTIFICATION_USER ON customer_notifications (user_id)');
        $this->addSql('CREATE INDEX IDX_CUSTOMER_NOTIFICATION_STORE ON customer_notifications (store_id)');
        $this->addSql('CREATE INDEX IDX_CUSTOMER_NOTIFICATION_ORDER ON customer_notifications (related_order_id)');
        $this->addSql('ALTER TABLE customer_notifications ADD CONSTRAINT FK_CUSTOMER_NOTIFICATION_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer_notifications ADD CONSTRAINT FK_CUSTOMER_NOTIFICATION_STORE FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer_notifications ADD CONSTRAINT FK_CUSTOMER_NOTIFICATION_ORDER FOREIGN KEY (related_order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE customer_notifications DROP CONSTRAINT FK_CUSTOMER_NOTIFICATION_USER');
        $this->addSql('ALTER TABLE customer_notifications DROP CONSTRAINT FK_CUSTOMER_NOTIFICATION_STORE');
        $this->addSql('ALTER TABLE customer_notifications DROP CONSTRAINT FK_CUSTOMER_NOTIFICATION_ORDER');
        $this->addSql('DROP TABLE customer_notifications');
    }
}
