<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260629030403 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cards (id UUID NOT NULL, oracle_id UUID NOT NULL, name VARCHAR(255) NOT NULL, set_code VARCHAR(10) NOT NULL, collector_number VARCHAR(20) NOT NULL, rarity VARCHAR(20) DEFAULT NULL, mana_cost VARCHAR(64) DEFAULT NULL, type_line VARCHAR(255) DEFAULT NULL, oracle_text TEXT DEFAULT NULL, cmc DOUBLE PRECISION DEFAULT NULL, image_uris JSON DEFAULT NULL, prices JSON DEFAULT NULL, scryfall_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CARD_NAME ON cards (name)');
        $this->addSql('CREATE INDEX IDX_CARD_ORACLE_ID ON cards (oracle_id)');
        $this->addSql('CREATE TABLE inventory_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, price_cents INT NOT NULL, condition VARCHAR(255) NOT NULL, is_foil BOOLEAN NOT NULL, notes TEXT DEFAULT NULL, store_id INT NOT NULL, card_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3D82424DB092A811 ON inventory_items (store_id)');
        $this->addSql('CREATE INDEX IDX_3D82424D4ACC9A20 ON inventory_items (card_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_INVENTORY_STORE_CARD ON inventory_items (store_id, card_id, condition, is_foil)');
        $this->addSql('CREATE TABLE stores (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D5907CCC7E3C61F9 ON stores (owner_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_STORE_SLUG ON stores (slug)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, display_name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_EMAIL ON users (email)');
        $this->addSql('ALTER TABLE inventory_items ADD CONSTRAINT FK_3D82424DB092A811 FOREIGN KEY (store_id) REFERENCES stores (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_items ADD CONSTRAINT FK_3D82424D4ACC9A20 FOREIGN KEY (card_id) REFERENCES cards (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stores ADD CONSTRAINT FK_D5907CCC7E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE inventory_items DROP CONSTRAINT FK_3D82424DB092A811');
        $this->addSql('ALTER TABLE inventory_items DROP CONSTRAINT FK_3D82424D4ACC9A20');
        $this->addSql('ALTER TABLE stores DROP CONSTRAINT FK_D5907CCC7E3C61F9');
        $this->addSql('DROP TABLE cards');
        $this->addSql('DROP TABLE inventory_items');
        $this->addSql('DROP TABLE stores');
        $this->addSql('DROP TABLE users');
    }
}
