<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260702002000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Store payment provider connections';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE store_payment_accounts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, store_id INT NOT NULL, provider VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, environment VARCHAR(32) NOT NULL, provider_merchant_id VARCHAR(128) DEFAULT NULL, provider_location_id VARCHAR(128) DEFAULT NULL, access_token_encrypted TEXT DEFAULT NULL, refresh_token_encrypted TEXT DEFAULT NULL, scopes JSON NOT NULL, token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, connected_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disconnected_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_error TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_STORE_PAYMENT_STORE ON store_payment_accounts (store_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_STORE_PAYMENT_PROVIDER ON store_payment_accounts (store_id, provider)');
        $this->addSql('ALTER TABLE store_payment_accounts ADD CONSTRAINT FK_STORE_PAYMENT_STORE FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE store_payment_accounts DROP CONSTRAINT FK_STORE_PAYMENT_STORE');
        $this->addSql('DROP TABLE store_payment_accounts');
    }
}
