<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260630060000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Align CSV import job id generation with Doctrine mapping.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE csv_import_jobs ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE csv_import_jobs ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE csv_import_jobs ALTER id DROP IDENTITY IF EXISTS');
        $this->addSql("ALTER TABLE csv_import_jobs ALTER id SET DEFAULT nextval('csv_import_jobs_id_seq')");
    }
}
