<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260630040000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add store customer profiles, favorites, and want list entries.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE store_customers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, store_id INT NOT NULL, phone VARCHAR(255) DEFAULT NULL, shipping_address TEXT DEFAULT NULL, payment_brand VARCHAR(40) DEFAULT NULL, payment_last4 VARCHAR(4) DEFAULT NULL, payment_expires VARCHAR(7) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_STORE_CUSTOMER_USER_STORE ON store_customers (user_id, store_id)');
        $this->addSql('CREATE INDEX IDX_3F05225CA76ED395 ON store_customers (user_id)');
        $this->addSql('CREATE INDEX IDX_3F05225CB092A811 ON store_customers (store_id)');
        $this->addSql('CREATE TABLE customer_favorites (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, customer_id INT NOT NULL, inventory_item_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CUSTOMER_FAVORITE_ITEM ON customer_favorites (customer_id, inventory_item_id)');
        $this->addSql('CREATE INDEX IDX_4F9498EF9395C3F3 ON customer_favorites (customer_id)');
        $this->addSql('CREATE INDEX IDX_4F9498EF536BF4A2 ON customer_favorites (inventory_item_id)');
        $this->addSql('CREATE TABLE customer_want_list_entries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, customer_id INT NOT NULL, card_id UUID DEFAULT NULL, card_name VARCHAR(255) NOT NULL, set_code VARCHAR(120) DEFAULT NULL, is_foil BOOLEAN NOT NULL, quantity INT NOT NULL, notes VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F6E789A59395C3F3 ON customer_want_list_entries (customer_id)');
        $this->addSql('CREATE INDEX IDX_F6E789A54ACC9A20 ON customer_want_list_entries (card_id)');
        $this->addSql('ALTER TABLE store_customers ADD CONSTRAINT FK_STORE_CUSTOMERS_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_customers ADD CONSTRAINT FK_STORE_CUSTOMERS_STORE FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_favorites ADD CONSTRAINT FK_CUSTOMER_FAVORITES_CUSTOMER FOREIGN KEY (customer_id) REFERENCES store_customers (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_favorites ADD CONSTRAINT FK_CUSTOMER_FAVORITES_ITEM FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_want_list_entries ADD CONSTRAINT FK_CUSTOMER_WANT_LIST_CUSTOMER FOREIGN KEY (customer_id) REFERENCES store_customers (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_want_list_entries ADD CONSTRAINT FK_CUSTOMER_WANT_LIST_CARD FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE customer_want_list_entries DROP CONSTRAINT FK_CUSTOMER_WANT_LIST_CARD');
        $this->addSql('ALTER TABLE customer_want_list_entries DROP CONSTRAINT FK_CUSTOMER_WANT_LIST_CUSTOMER');
        $this->addSql('ALTER TABLE customer_favorites DROP CONSTRAINT FK_CUSTOMER_FAVORITES_ITEM');
        $this->addSql('ALTER TABLE customer_favorites DROP CONSTRAINT FK_CUSTOMER_FAVORITES_CUSTOMER');
        $this->addSql('ALTER TABLE store_customers DROP CONSTRAINT FK_STORE_CUSTOMERS_STORE');
        $this->addSql('ALTER TABLE store_customers DROP CONSTRAINT FK_STORE_CUSTOMERS_USER');
        $this->addSql('DROP TABLE customer_want_list_entries');
        $this->addSql('DROP TABLE customer_favorites');
        $this->addSql('DROP TABLE store_customers');
    }
}
