<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260701221845 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Customer per-store shopping cart (cart_items)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE cart_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, customer_id INT NOT NULL, inventory_item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BEF484459395C3F3 ON cart_items (customer_id)');
        $this->addSql('CREATE INDEX IDX_BEF48445536BF4A2 ON cart_items (inventory_item_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CART_CUSTOMER_ITEM ON cart_items (customer_id, inventory_item_id)');
        $this->addSql('ALTER TABLE cart_items ADD CONSTRAINT FK_BEF484459395C3F3 FOREIGN KEY (customer_id) REFERENCES store_customers (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cart_items ADD CONSTRAINT FK_BEF48445536BF4A2 FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE cart_items DROP CONSTRAINT FK_BEF484459395C3F3');
        $this->addSql('ALTER TABLE cart_items DROP CONSTRAINT FK_BEF48445536BF4A2');
        $this->addSql('DROP TABLE cart_items');
    }
}
