<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260630050000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Align CSV import and customer schema with Doctrine mappings.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE csv_import_jobs DROP COLUMN IF EXISTS rows');
        $this->addSql('ALTER TABLE csv_import_jobs ALTER error_message TYPE VARCHAR(255)');
        $this->addSql('ALTER INDEX IF EXISTS idx_6d2e20b4a76ed395 RENAME TO IDX_6858EE6EB092A811');

        $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF (
        SELECT identity_generation
        FROM information_schema.columns
        WHERE table_name = 'store_customers' AND column_name = 'id'
    ) IS NULL THEN
        ALTER TABLE store_customers ALTER id DROP DEFAULT;
        ALTER TABLE store_customers ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;
SQL);
        $this->addSql('ALTER INDEX IF EXISTS idx_store_customers_user RENAME TO IDX_3F05225CA76ED395');
        $this->addSql('ALTER INDEX IF EXISTS idx_store_customers_store RENAME TO IDX_3F05225CB092A811');

        $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF (
        SELECT identity_generation
        FROM information_schema.columns
        WHERE table_name = 'customer_favorites' AND column_name = 'id'
    ) IS NULL THEN
        ALTER TABLE customer_favorites ALTER id DROP DEFAULT;
        ALTER TABLE customer_favorites ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;
SQL);
        $this->addSql('ALTER INDEX IF EXISTS idx_customer_favorites_customer RENAME TO IDX_4F9498EF9395C3F3');
        $this->addSql('ALTER INDEX IF EXISTS idx_customer_favorites_item RENAME TO IDX_4F9498EF536BF4A2');

        $this->addSql(<<<'SQL'
DO $$
BEGIN
    IF (
        SELECT identity_generation
        FROM information_schema.columns
        WHERE table_name = 'customer_want_list_entries' AND column_name = 'id'
    ) IS NULL THEN
        ALTER TABLE customer_want_list_entries ALTER id DROP DEFAULT;
        ALTER TABLE customer_want_list_entries ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;
SQL);
        $this->addSql('ALTER INDEX IF EXISTS idx_customer_want_list_customer RENAME TO IDX_F6E789A59395C3F3');
        $this->addSql('ALTER INDEX IF EXISTS idx_customer_want_list_card RENAME TO IDX_F6E789A54ACC9A20');

        $this->addSql('ALTER TABLE csv_import_rows ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE csv_import_rows ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        $this->addSql("ALTER TABLE csv_import_jobs ADD COLUMN rows JSON NOT NULL DEFAULT '[]'");
        $this->addSql('ALTER TABLE csv_import_jobs ALTER error_message TYPE TEXT');
        $this->addSql('ALTER INDEX IF EXISTS IDX_6858EE6EB092A811 RENAME TO idx_6d2e20b4a76ed395');

        $this->addSql('ALTER TABLE store_customers ALTER id DROP IDENTITY IF EXISTS');
        $this->addSql("ALTER TABLE store_customers ALTER id SET DEFAULT nextval('store_customers_id_seq')");
        $this->addSql('ALTER INDEX IF EXISTS IDX_3F05225CA76ED395 RENAME TO idx_store_customers_user');
        $this->addSql('ALTER INDEX IF EXISTS IDX_3F05225CB092A811 RENAME TO idx_store_customers_store');

        $this->addSql('ALTER TABLE customer_favorites ALTER id DROP IDENTITY IF EXISTS');
        $this->addSql("ALTER TABLE customer_favorites ALTER id SET DEFAULT nextval('customer_favorites_id_seq')");
        $this->addSql('ALTER INDEX IF EXISTS IDX_4F9498EF9395C3F3 RENAME TO idx_customer_favorites_customer');
        $this->addSql('ALTER INDEX IF EXISTS IDX_4F9498EF536BF4A2 RENAME TO idx_customer_favorites_item');

        $this->addSql('ALTER TABLE customer_want_list_entries ALTER id DROP IDENTITY IF EXISTS');
        $this->addSql("ALTER TABLE customer_want_list_entries ALTER id SET DEFAULT nextval('customer_want_list_entries_id_seq')");
        $this->addSql('ALTER INDEX IF EXISTS IDX_F6E789A59395C3F3 RENAME TO idx_customer_want_list_customer');
        $this->addSql('ALTER INDEX IF EXISTS IDX_F6E789A54ACC9A20 RENAME TO idx_customer_want_list_card');

        $this->addSql('ALTER TABLE csv_import_rows ALTER id DROP IDENTITY IF EXISTS');
        $this->addSql("ALTER TABLE csv_import_rows ALTER id SET DEFAULT nextval('csv_import_rows_id_seq')");
    }
}
